# Install the pre-commit hooks below with
# 'pre-commit install'

# Auto-update the version of the hooks with
# 'pre-commit autoupdate'

# Run the hooks on all files with
# 'pre-commit run --all'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: check-ast
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
    exclude: |
      (?x)^(
          examples/k8s/svc-acct\.yaml |
          ci/k8s/indexed-job\.yaml
      )$
  - id: end-of-file-fixer
    # only include python files
    files: \.py$
  - id: debug-statements
    # only include python files
    files: \.py$
  - id: trailing-whitespace
    # only include python files
    files: \.py$

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 54a455f7ce629598b7535ff828fd5fb796f4b83f  # frozen: v0.12.9
  hooks:
  - id: ruff

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: '412de98d50e846f31ea6f4b0ad036f2c24a7a024'  # frozen: v1.17.1
  hooks:
  - id: mypy
    files: (jax/|tests/typing_test\.py)
    exclude: jax/_src/basearray.py|jax/numpy/__init__.py|jax/nn/__init__.py|jaxlib/_jax/.*  # Use pyi instead
    additional_dependencies: [types-requests==2.31.0, numpy>=2.2.0]
    args: [--config=pyproject.toml]

- repo: https://github.com/mwouts/jupytext
  rev: 8ed836db64ad5d304f2315e6bfd9049c9142e190  # frozen: v1.16.4
  hooks:
  - id: jupytext
    files: docs/
    args: [--sync]
