# Install the pre-commit hooks below with
# 'pre-commit install'

# Auto-update the version of the hooks with
# 'pre-commit autoupdate'

# Run the hooks on all files with
# 'pre-commit run --all'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: check-ast
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
    exclude: |
      (?x)^(
          examples/k8s/svc-acct\.yaml |
          ci/k8s/indexed-job\.yaml
      )$
  - id: end-of-file-fixer
    # only include python files
    files: \.py$
  - id: debug-statements
    # only include python files
    files: \.py$
  - id: trailing-whitespace
    # only include python files
    files: \.py$

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 0470f7c8a653e950f7cc5a653204ceb3fde4c02a  # frozen: v0.15.1
  hooks:
  - id: ruff

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: a66e98df7b4aeeb3724184b332785976d062b92e  # frozen: v1.19.1
  hooks:
  - id: mypy
    files: (jax/|tests/typing_test\.py)
    exclude: jax/_src/basearray.py|jax/numpy/__init__.py|jax/nn/__init__.py|jaxlib/_jax/.*  # Use pyi instead
    additional_dependencies: [types-requests==2.31.0, numpy~=2.3.0, scipy-stubs]
    args: [--config=pyproject.toml]

- repo: https://github.com/mwouts/jupytext
  rev: 8ed836db64ad5d304f2315e6bfd9049c9142e190  # frozen: v1.16.4
  hooks:
  - id: jupytext
    files: docs/
    args: [--sync]

# This is a manual-only pre-commit hook to run pyrefly type checks. To run it:
# $ pre-commit run --hook-stage manual pyrefly-check --all-files
- repo: https://github.com/facebook/pyrefly-pre-commit
  rev: 9a1f9496fbaeef712203986d6953bb573f2511fe  # frozen: v0.52.0
  hooks:
    - id: pyrefly-check
      name: Pyrefly (type checking)
      pass_filenames: false
      additional_dependencies: [types-requests==2.31.0, numpy~=2.3.0, ml_dtypes~=0.5.0, scipy-stubs]
      stages: [manual]
