# Copyright 2022 The JAX Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI - NVIDIA GPU (nightly)

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 12 * * *" # Daily at 12:00 UTC
  workflow_dispatch: # allows triggering the workflow run manually
jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      # Secrets to connect and authenticate with the Cluster manager web API
      WEB_API_TOKEN: ${{ secrets.NV_CLUSTER_API_TOKEN }}
      WEB_API_URL:   ${{ secrets.NV_CLUSTER_API_URL }}
      
      GITHUB_WORKSPACE_REMOTE: "~/jax_ci_${{ github.run_id }}_${{ github.run_attempt }}/"
      CONFIG: "-F ${{ github.workspace }}/.ssh/config -o UserKnownHostsFile=${{ github.workspace }}/.ssh/known_hosts"
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # ratchet:actions/checkout@v4
      - uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984 # ratchet:actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Create credentials
        run: |

          # Create SSH keys
          mkdir -p ./.ssh && chmod 700 ./.ssh
          ssh-keygen -N '' -f ./.ssh/id_rsa

      - name: Create cluster
        run: |

          # Setup cluster, get username and IP address
          pip install -r "./.github/workflows/slurm_job_scripts/requirements.txt"
          python3 ./.github/workflows/slurm_job_scripts/oci_cluster_manager.py create_cluster --pubkey "$(cat ./.ssh/id_rsa.pub)" &> oci_automation_create.log
          USER=$(tail -n 2 oci_automation_create.log | head -n 1)
          IP=$(tail -n 1 oci_automation_create.log)

          # Hide IP address from logs
          echo "::add-mask::${IP}"

          # Create SSH config
          grep "^${IP} " oci_automation_create.log >> ./.ssh/known_hosts
          echo "Host headnode
            User ${USER}
            HostName ${IP}
            IdentityFile ${GITHUB_WORKSPACE}/.ssh/id_rsa
            ServerAliveInterval 30" > ./.ssh/config

      - name: Check SLURM is working
        run: |

          # SSH into the cluser & check SLURM
          ssh ${CONFIG} headnode sinfo

          # Run dummy job
          SRUN="srun --container-name=nvidia --container-image=docker://nvcr.io#nvidia/tensorflow:22.11-tf2-py3 -N 2 -t 15:00 --gpus-per-node=8 --cpus-per-task=8 --ntasks-per-node=8"
          CMD="bash -c 'hostname && nvidia-smi --query-gpu=gpu_name,driver_version --format=csv'"
          ssh ${CONFIG} headnode "${SRUN} ${CMD}"

      - name: Copy workspace
        run: |

          ssh ${CONFIG} headnode "rm -rf ${GITHUB_WORKSPACE_REMOTE} && mkdir -p ${GITHUB_WORKSPACE_REMOTE}"
          scp ${CONFIG} -r ./.github     headnode:${GITHUB_WORKSPACE_REMOTE}/.github
          scp ${CONFIG} -r ./tests       headnode:${GITHUB_WORKSPACE_REMOTE}/tests

      - name: T5X end-to-end tests
        timeout-minutes: 25
        run: |

          ENV="GITHUB_WORKSPACE_REMOTE=${GITHUB_WORKSPACE_REMOTE}"
          SALLOC="salloc -N 2 --gpus-per-node=8 --exclusive -t 0:20:00 -p compute"
          CMD="bash ${GITHUB_WORKSPACE_REMOTE}/.github/workflows/slurm_job_scripts/run_e2e_t5x_tests.sub"
          ssh ${CONFIG} headnode "${ENV} ${SALLOC} ${CMD}"

      - name: Gather results
        if: always()
        run: |

          scp ${CONFIG} -r headnode:${GITHUB_WORKSPACE_REMOTE}/outputs ./

      - name: Destroy cluster
        if: always()
        run: |

          pip install -r "./.github/workflows/slurm_job_scripts/requirements.txt"
          python3 ./.github/workflows/slurm_job_scripts/oci_cluster_manager.py destroy_clusters &> ./oci_automation_destroy.log

      - name: Upload run results from all nodes
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # ratchet:actions/upload-artifact@v3
        if: always()
        with:
          name: output-from-nodes
          path: "outputs/*.txt"

  report-metrics:
    name: e2e-tests-metrics
    needs: tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # ratchet:actions/checkout@v4
      - uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984 # ratchet:actions/setup-python@v4
        with:
          python-version: "3.x"
      - uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7 # ratchet:actions/download-artifact@v3
        with:
          path: /tmp/workspace/logs
      - name: Parse log output
        run: |
          ls /tmp/workspace/logs/output-from-nodes/ && mv /tmp/workspace/logs/output-from-nodes/output*t5x*1-0-0.txt ${GITHUB_WORKSPACE}/output.log
          pip install -r "${GITHUB_WORKSPACE}/.github/workflows/slurm_job_scripts/requirements.txt"
          python ${GITHUB_WORKSPACE}/.github/workflows/slurm_job_scripts/extract_e2e_tests_metrics.py --logfile ${GITHUB_WORKSPACE}/output.log --outmd ${GITHUB_WORKSPACE}/report.md --outjson ${GITHUB_WORKSPACE}/report.json --name end-to-end-t5x
          cat report.md >> $GITHUB_STEP_SUMMARY

  report:
    name: report
    needs: tests
    if: |
      failure()
      && github.event_name == 'schedule'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # ratchet:actions/checkout@v4
      - uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984 # ratchet:actions/setup-python@v4
        with:
          python-version: "3.x"
      - uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7 # ratchet:actions/download-artifact@v3
        with:
          path: /tmp/workspace/logs
      - name: Parse log output
        run: |
          ls /tmp/workspace/logs/output-from-nodes/
          python .github/workflows/cat_slurm_logs.py /tmp/workspace/logs/output-from-nodes/*.txt --outfile=parsed-logs.txt
      - name: Report failures
        uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0 # ratchet:actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const parsed_logs = fs.readFileSync('parsed-logs.txt', 'utf8');
            const title = "⚠️ Nightly GPU Multiprocess CI failed ⚠️"
            const workflow_url = `https://github.com/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`
            const issue_body = `[Workflow Run URL](${workflow_url})\n${parsed_logs}`
            // Run GraphQL query against GitHub API to find the most recent open issue used for reporting failures
            const query = `query($owner:String!, $name:String!, $creator:String!, $label:String!){
              repository(owner: $owner, name: $name) {
                issues(first: 1, states: OPEN, filterBy: {createdBy: $creator, labels: [$label]}, orderBy: {field: CREATED_AT, direction: DESC}) {
                  edges {
                    node {
                      body
                      id
                      number
                    }
                  }
                }
              }
            }`;
            const variables = {
                owner: context.repo.owner,
                name: context.repo.repo,
                label: 'Nightly-CI',
                creator: "github-actions[bot]"
            }
            const result = await github.graphql(query, variables)
            // If no issue is open, create a new issue,
            // else update the body of the existing issue.
            if (result.repository.issues.edges.length === 0) {
                github.rest.issues.create({
                    owner: variables.owner,
                    repo: variables.name,
                    body: issue_body,
                    title: title,
                    labels: [variables.label]
                })
            } else {
                github.rest.issues.update({
                    owner: variables.owner,
                    repo: variables.name,
                    issue_number: result.repository.issues.edges[0].node.number,
                    body: issue_body
                })
            }
