name: Wheel build - Windows CPU x86_64
on:
  workflow_dispatch: # allows triggering the workflow run manually

env:
  DISTUTILS_USE_SDK: 1
  MSSdk: 1

jobs:
  win-wheels:
    strategy:
      fail-fast: false  # Don't stop all wheel builds if one has a test failure.
      matrix:
        os: [win-2019-16core]
        arch: [AMD64]
        pyver: ['3.9', '3.10', '3.11', '3.12.0-rc.3']
    name: ${{ matrix.os }} ${{ matrix.pyver }} jaxlib wheel build
    runs-on: ${{ matrix.os }}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # ratchet:actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.pyver }}
          cache: 'pip'

      - name: Build wheels
        env:
          BAZEL_VC: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC"
          JAXLIB_RELEASE: true
        run: |
          python -m pip install -r build/test-requirements.txt
          "C:\\msys64\\;C:\\msys64\\usr\\bin\\;" >> $env:GITHUB_PATH
          python.exe build\build.py --bazel_options=--color=yes --verbose

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ${{ github.workspace }}\dist\*.whl
          retention-days: 5

      - name: Run tests
        env:
          JAX_ENABLE_CHECKS: true
          JAX_SKIP_SLOW_TESTS: true
          PY_COLORS: 1
        run: |
          python -m pip install -e ${{ github.workspace }}
          python -m pip install --no-index --find-links ${{ github.workspace }}\dist jaxlib
          echo "JAX_ENABLE_CHECKS=$JAX_ENABLE_CHECKS"
          pytest -n auto --tb=short tests examples