name: CI - Windows CPU
on:
  schedule:
    - cron: "0 12 * * *" # Daily at 12:00 UTC
  workflow_dispatch: # allows triggering the workflow run manually
  pull_request:
    types: [ labeled ] # allow force-windows-run label

env:
  DISTUTILS_USE_SDK: 1
  MSSdk: 1

jobs:
  win-wheels:
    if: ${{ (github.event.action != 'labeled') || (github.event.label.name == 'windows:force-run')}}
    strategy:
      fail-fast: true
      matrix:
        os: [windows-2019-32core]
        arch: [AMD64]
        pyver: ['3.9']
    name: ${{ matrix.os }} CI build
    runs-on: ${{ matrix.os }}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # ratchet: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Install LLVM/Clang
        run: choco install llvm --version=18.1.4 --yes --no-progress --allow-downgrade

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # ratchet:actions/checkout@v4
        with:
          path: jax

      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # ratchet:actions/setup-python@v5
        with:
          python-version: ${{ matrix.pyver }}
          cache: 'pip'

      - name: Build wheels
        env:
          BAZEL_VC: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC"
          JAXLIB_NIGHTLY: true  # Tag the wheels as dev versions
        run: |
          cd jax
          python -m pip install -r build/test-requirements.txt
          python -m pip install --upgrade numpy==2.0.0 scipy==1.13.1
          "C:\\msys64\\;C:\\msys64\\usr\\bin\\;" >> $env:GITHUB_PATH
          python.exe build\build.py `
            --bazel_options=--color=yes `
            --bazel_options=--config=win_clang

      - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # ratchet: actions/upload-artifact@v4
        with:
          name: wheels
          path: ${{ github.workspace }}\jax\dist\*.whl
          retention-days: 5

      - name: Run tests
        env:
          JAX_ENABLE_CHECKS: true
          JAX_SKIP_SLOW_TESTS: true
          PY_COLORS: 1
        run: |
          cd jax
          python -m pip install -e ${{ github.workspace }}\jax
          python -m pip install --no-index --find-links ${{ github.workspace }}\jax\dist jaxlib
          echo "JAX_ENABLE_CHECKS=$JAX_ENABLE_CHECKS"
          pytest -n auto --tb=short tests examples
